project:
  type: website
  output-dir: docs

website:
  title: "What's new in the tidyverse"
  site-url: "https://ivelasq.github.io/2023-03-22_whats-new-in-the-tidyverse"
  description: "Talk for R-Ladies Rome"
  twitter-card:
    title: "What's new in the tidyverse"
    description: "Talk for R-Ladies Rome"
    image: profile2.png
    creator: "@ivelasq3"
    site: "@ivelasq3"
  open-graph:
    title: "What's new in the tidyverse"
    description: "2023-03-22 R-Ladies Rome Presentation"
    image: profile2.png
  navbar:
    pinned: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/ivelasq/2023-03-22_whats-new-in-the-tidyverse
      - icon: twitter
        href: https://twitter.com/ivelasq3
  page-footer: 
    right: 
      - icon: github
        href: https://github.com/ivelasq/2023-03-22_whats-new-in-the-tidyverse
      - icon: twitter 
        href: https://twitter.com/ivelasq3
    left:
      - file: colophon.qmd
  
format:
  html:
    theme: [litera, styles.scss]
    highlight-style: tango
    code-copy: true
    code-overflow: wrap
    code-link: true
    resources: profile2.png
editor: source

execute: 
  freeze: auto
